baseURL: https://agomezguru.github.io/
languageCode: es
title: GitHub Blog
theme: "designblog-liberty"
enableEmoji: true
pagination:
  pagerSize: 4

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      # Permite que Hugo renderice HTML que no es seguro, como los iframes.
      unsafe: true
