description: "Mi blog personal en GitHub"
copyright: "&copy; 2023 GitHub Blog: Made with"
stack: "Coded with [Hugo](https://gohugo.io/); Designed by [**W3layouts**](https://w3layouts.com/)"
errorPage:
  title: Página no encontrada
  warning: En este momento no puedo ubicar lo que buscas, probablemente mi blog está desconectado 
    para mejorarlo aún más. Por favor vuelve más tarde y mira todas las novedades que tengo para tí.
  returnURL: /
  returnText: Regresar

homeBlocks:
  featured: Artículos seleccionados
  trendsUp: Lo más visto
  alone: true
  highlights: Today Highligths
  recent: Escritos recientes
  trendsDown: Tendencia

author:
  name: agomezguru
  real_name: Alejandro Gómez Lagunas
  location: Oaxaca, Méx.
  phone: +52 (951) 228-6616
  linkedin: https://www.linkedin.com/in/alejandro-g%C3%B3mez-lagunas-12748212/
  github: https://github.com/agomezguru
  email: alagunas@coati.com.mx
  url: /acerca_de
  about:
    Apasionado por las grabaciones musicales de calidad excelsa (entusiasta de los equipos de audio de alta
    gama), me encanta caminar al aire libre o en una playa aislada, me gusta nadar, amo la poesía,
    la literatura y una buena conversación.
  animation:
    first: Ing. Mecánico Eléctrico de Profesión
    middle: Programador por accidente, ahora con maestría
    last: Maestro en Administración de Empresas por necesidad